Project 2: Mobile Version
Paul-js-hub/portfolio pull request #2
Opened 2022-04-22 13:17 UTC by Paul-js-hub

### Portfolio Project 2
In this milestone I:

- Added CSS for the about myself section
- Added CSS and Html codes for the work section
- Added styling to the work section
- Added CSS to the list of items

2022-04-22 14:15 UTC, roshan-bajgain requested changes
Hi @Paul-js-hub , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KG5KpLlr1UEPvwgkiM/giphy.gif"/>

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight :tada: :champagne: 
- Nice PR description and title :+1: 
- Nice README file :heavy_check_mark:
- No linter error :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button (e.g., "See project") is a link a or button tag, and follow the button styling: Active, Hover, and Pressed (see design)

![hover](https://user-images.githubusercontent.com/81727988/164728933-18b02dbb-83cb-4ac6-8ec9-a539021bb373.png)

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button (e.g., "See project") is a link a or button tag, and follow the button styling: Active, Hover, and Pressed (see design)

![hover](https://user-images.githubusercontent.com/81727988/164728933-18b02dbb-83cb-4ac6-8ec9-a539021bb373.png)

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button (e.g., "See project") is a link a or button tag, and follow the button styling: Active, Hover, and Pressed (see design)

![hover](https://user-images.githubusercontent.com/81727988/164728933-18b02dbb-83cb-4ac6-8ec9-a539021bb373.png)

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button (e.g., "See project") is a link a or button tag, and follow the button styling: Active, Hover, and Pressed (see design)

![hover](https://user-images.githubusercontent.com/81727988/164728933-18b02dbb-83cb-4ac6-8ec9-a539021bb373.png)

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] Kindly implement the spacing equally from both sides left and right to stick with the Figma design. Implement in all the section
- your design
![his design](https://user-images.githubusercontent.com/81727988/164730598-63d3658b-765b-467d-bc5e-af17e4eca0b0.png)

- Figma design
![figma](https://user-images.githubusercontent.com/81727988/164730678-acf53360-21fd-4425-ae5d-9df12031a4e8.png)

2022-04-22 14:15 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] Kindly stick as much as possible to Figma design. Implement the `Epplise` on all the sections in your project.

## Figma design

![design](https://user-images.githubusercontent.com/81727988/164731618-4be30a4f-6d1d-4e47-9ae1-87b40a68752b.png)

2022-04-22 22:10 UTC, Paul-js-hub commented
@roshan-bajgain does press mean to focus?

2022-04-23 04:00 UTC, Paul-js-hub commented on index.html
> +          </div>
@roshan-bajgain is button pressed means to focus? Is enabled the one that is default

2022-04-23 06:12 UTC, Paul-js-hub commented on index.html
> +          </div>
@roshan-bajgain what do you mean by is a link a or button tag? I included a button tag as you can see in the HTML codes

2022-04-23 07:08 UTC, rukundoeric approved these changes
Hi @Paul-js-hub,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

2022-04-23 09:25 UTC, merged